branches: main
matrix:
    GOTIFY_VERSION:
        - 2.2.0
pipeline:
    build:
        image: registry.home.estelsmith.com/alpine:3.17
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - registry_username
            - registry_password
        commands:
            - apk --no-cache add docker-cli docker-cli-buildx
            - >
                docker login
                -u $${REGISTRY_USERNAME}
                -p $${REGISTRY_PASSWORD}
                registry.home.estelsmith.com
            - >
                docker buildx build .
                --build-arg GOTIFY_VERSION="${GOTIFY_VERSION}"
                -t registry.home.estelsmith.com/gotify-docker:latest
                -t registry.home.estelsmith.com/gotify-docker:${GOTIFY_VERSION}-${CI_BUILD_NUMBER}
                --output type=registry
