branches: main
pipeline:
    build:
        image: registry.home.estelsmith.com/alpine:3.17
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - registry_username
            - registry_password
        commands:
            - apk --no-cache add docker-cli
            - docker login -u $${REGISTRY_USERNAME} -p $${REGISTRY_PASSWORD} registry.home.estelsmith.com
            - >
                docker buildx build .
                -t registry.home.estelsmith.com/gotify-docker:latest
                -t registry.home.estelsmith.com/gotify-docker:0.0.${CI_BUILD_NUMBER}
                --output type=registry
